apiVersion: v1
kind: Service
metadata:
  name: briangautreau-com-svc
  labels:
    app.kubernetes.io/name: briangautreau-com
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: briangautreau-com
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
